<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="svg.js" defer></script>
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>
<body>
<h1>Generateur de Rectangle</h1>
    
        <label for="couleur">Choisir une couleur pour les cercles: </label>
        <select name="couleur" id="couleur">
            <!-- <option value="">--Choisis un nbre de para--</option> -->
            <option value="blue" >bleu</option>
            <option value="red">rouge</option>
            <option value="purple">violet</option>
            <option value="green">vert</option>
            <option value="black">noir</option>
            <option value="pink">rose</option>
        </select>
        <br><br>
        <label for="opaci">Choisir une opacité: </label>
        <select name="opaci" id="opaci">
            <!-- <option value="">--Choisis un nbre de para--</option> -->
            <option value="0.1" >0.1</option>
            <option value="0.3">0.3</option>
            <option value="0.5">0.5</option>
            <option value="0.7">0.7</option>
            <option value="0.85">0.85</option>
            <option value="1">1</option>
        </select>

    <br><br>
    <svg>
        <?= genRect(60,50,100,75,'green',0.5); ?>
    </svg>
    <svg>
        <?= genCircle(60,60,50, $couleur ,$opaci); ?>
    </svg>
    <svg>
        <?= genEllipse(100,60,20,40,'green',0.5); ?>
    </svg>
    <br>
    <svg>
        <?= genSquare(50,25,75,'green',0.5); ?>
    </svg>
    <svg>
        <?= genTriangle(10,10,150,150,200,45,'green',0.5); ?>
    </svg>
    <br>
    <svg class="grand">
        <?= genRect(60,50,100,75,'green',0.5); ?>
        <?= genCircle(60,60,50,'green',0.5); ?>
        <?= genEllipse(100,60,20,40,'green',0.5); ?>
        <?= genSquare(50,25,75,'green',0.5); ?>
        <?= genTriangle(10,10,150,150,200,45,'green',0.5); ?>

    </svg>
    <br><br>
    <section>
        <?=$svg; ?>
    </section>
</body>
</html>