<!-- Formulaire construction rectangle -->
<fieldset>
    <legend>Dessine un rectangle</legend>
    <div>
        <label for="abscisse">Abscisse angle gauche</label>
        <input type="text" id="abscisse" name="abscisse">
    </div>
    <div>
        <label for="ordonnee">Ordonnée angle gauche</label>
        <input type="text" id="ordonnee" name="ordonnee">
    </div>
    <div>
        <label for="longueur">Longueur en pixel</label>
        <input type="text" id="longueur" name="longueur">
    </div>
    <div>
        <label for="largeur">Largeur en pixel</label>
        <input type="text" id="largeur" name="largueur">
    </div>
    <div>
        <label for="couleur">Choisir une forme: </label>
        <select name="couleur" id="couleur">
            <option value="">--Choisis une couleur--</option>
            <option value="blue" >Bleu</option>
            <option value="red">Rouge</option>
            <option value="green">Vert</option>
            <option value="yellow">Jaune</option>
            <option value="pink">Rose</option>
            <option value="orange">Orange</option>
            <option value="black">Noir</option>
        </select>
    </div>
    <div>
        <label for="opacite">Opacité</label>
        <input type="text" id="opacite" name="opacite">
    </div>
</fieldset>
